name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/.git*'
      - '**/*ignore'
      - '**/*rc.json'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    paths-ignore:
      - '**/*.md'
      - '**/.git*'
      - '**/*ignore'
      - '**/*rc.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true


jobs:
  build:
    name: 빌드
    runs-on: ubuntu-latest
    steps:
      - name: 소스코드 저장소 체크아웃
        uses: actions/checkout@v5
      - name: PNPM 설치
        uses: pnpm/action-setup@v4
        with:
          run_install: false # 캐시 사용을 위해 자동 설치 비활성화
      - name: Node.js 설치
        uses: actions/setup-node@v5
        with:
          node-version-file: ".node-version"
          cache: pnpm
      - name: 의존성 설치
        run: pnpm install --frozen-lockfile
      - name: 프로젝트 빌드
        run: pnpm build
      - name: 빌드 아티팩트 업로드
        uses: actions/upload-artifact@v5
        with:
          name: bingsu-${{ github.sha }}
          path: ./.output/
          retention-days: 7
          include-hidden-files: true
  sast:
    name: 정적 분석
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      security-events: write
    steps:
      - name: 소스코드 저장소 체크아웃
        uses: actions/checkout@v5
      - name: CodeQL 초기화
        uses: github/codeql-action/init@v3
        with:
          queries: security-and-quality
          languages: typescript
          build-mode: none
      - name: 빌드 아티팩트 다운로드
        uses: actions/download-artifact@v6
        with:
          name: bingsu-${{ github.sha }}
          path: ./.output/
      - name: CodeQL 분석 실행
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:typescript"
