name: 정기 보안 검사

on:
  schedule:
    - cron: '0 0 * * 1'  # 매주 월요일 자정에 실행

jobs:
  sast:
    name: 정적 분석
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: 소스코드 저장소 체크아웃
        uses: actions/checkout@v5
      - name: CodeQL 초기화
        uses: github/codeql-action/init@v3
        with:
          queries: security-and-quality
          languages: typescript
          build-mode: none
      - name: CodeQL 분석 실행
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:typescript"
